In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# Load dataset
df = pd.read_csv(r"../data/traffic_intelligence_dataset_1lakh.csv")


# Display first 5 rows
df.head()

,record_id,timestamp,location_name,latitude,longitude,road_type,lane_count,day_of_week,hour,is_weekend,...,signal_status,public_transport_delay_min,pollution_index_aqi,event_nearby,construction_work,accident_reported,accident_severity,prev_hour_congestion,congestion_level,target_congestion_next_hour
0,1,2024-01-01 00:04:00,Wakad Bridge,18.598795,73.763022,Highway,6,0,0,0,...,Working,3.6,55,0,1,0,NaN,Low,Low,Low
1,2,2024-01-01 00:09:00,Magarpatta Rd,18.515726,73.927038,Local,2,0,0,0,...,Working,0.4,59,0,0,0,NaN,Low,Low,Low
2,3,2024-01-01 00:11:00,Kharadi IT Park Rd,18.544116,73.934890,Highway,6,0,0,0,...,Working,1.6,67,0,0,0,NaN,Low,Low,Low
3,4,2024-01-01 00:15:00,Kothrud Depot,18.507846,73.801938,Local,2,0,0,0,...,Working,0.0,72,0,0,0,NaN,Low,Low,Low
4,5,2024-01-01 00:16:00,Swargate Signal,18.499092,73.859743,Local,2,0,0,0,...,Working,6.3,60,1,0,0,NaN,Low,Low,Low

# DATASET HEALTH CHECK

# Number of rows and columns

In [2]:
print("Number of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])

Number of Rows: 100000
Number of Columns: 31

# column names

In [3]:
print("Columns in Dataset:")
print(df.columns.tolist())

Columns in Dataset:
['record_id', 'timestamp', 'location_name', 'latitude', 'longitude', 'road_type', 'lane_count', 'day_of_week', 'hour', 'is_weekend', 'is_holiday', 'weather_condition', 'temperature_C', 'rainfall_mm', 'visibility_km', 'humidity_percent', 'wind_speed_kmph', 'vehicle_count', 'occupancy_percent', 'avg_speed_kmph', 'travel_time_index', 'signal_status', 'public_transport_delay_min', 'pollution_index_aqi', 'event_nearby', 'construction_work', 'accident_reported', 'accident_severity', 'prev_hour_congestion', 'congestion_level', 'target_congestion_next_hour']

## Data Type

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 31 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   record_id                    100000 non-null  int64
 1   timestamp                    100000 non-null  str
 2   location_name                100000 non-null  str
 3   latitude                     100000 non-null  float64
 4   longitude                    100000 non-null  float64
 5   road_type                    100000 non-null  str
 6   lane_count                   100000 non-null  int64
 7   day_of_week                  100000 non-null  int64
 8   hour                         100000 non-null  int64
 9   is_weekend                   100000 non-null  int64
 10  is_holiday                   100000 non-null  int64
 11  weather_condition            100000 non-null  str
 12  temperature_C                100000 non-null  float64
 13  rainfall_mm                  100000 non-null  float64
 14  visibility_km                100000 non-null  float64
 15  humidity_percent             100000 non-null  float64
 16  wind_speed_kmph              100000 non-null  float64
 17  vehicle_count                100000 non-null  int64
 18  occupancy_percent            100000 non-null  float64
 19  avg_speed_kmph               100000 non-null  float64
 20  travel_time_index            100000 non-null  float64
 21  signal_status                100000 non-null  str
 22  public_transport_delay_min   100000 non-null  float64
 23  pollution_index_aqi          100000 non-null  int64
 24  event_nearby                 100000 non-null  int64
 25  construction_work            100000 non-null  int64
 26  accident_reported            100000 non-null  int64
 27  accident_severity            2713 non-null    str
 28  prev_hour_congestion         100000 non-null  str
 29  congestion_level             100000 non-null  str
 30  target_congestion_next_hour  100000 non-null  str
dtypes: float64(11), int64(11), str(9)
memory usage: 30.2 MB

## statistical information

In [5]:
df.describe()

,record_id,latitude,longitude,lane_count,day_of_week,hour,is_weekend,is_holiday,temperature_C,rainfall_mm,...,wind_speed_kmph,vehicle_count,occupancy_percent,avg_speed_kmph,travel_time_index,public_transport_delay_min,pollution_index_aqi,event_nearby,construction_work,accident_reported
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,...,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000
mean,50000.500000,18.540913,73.842494,4.056280,2.989640,11.52519,0.284290,0.033420,27.005806,3.146869,...,7.981093,635.967630,53.550232,24.099464,2.489935,9.976069,92.50133,0.079150,0.100000,0.027130
std,28867.657797,0.051810,0.055655,1.360555,2.002422,6.93302,0.451078,0.179732,5.669897,8.199273,...,5.631734,536.977939,28.536916,11.184223,1.486879,10.601499,40.41135,0.269974,0.300002,0.162463
min,1.000000,18.446397,73.727449,2.000000,0.000000,0.00000,0.000000,0.000000,8.400000,0.000000,...,0.000000,37.000000,7.300000,2.900000,0.960000,0.000000,15.00000,0.000000,0.000000,0.000000
25%,25000.750000,18.504626,73.803392,4.000000,1.000000,5.00000,0.000000,0.000000,23.300000,0.000000,...,3.800000,268.000000,29.600000,15.400000,1.430000,2.700000,65.00000,0.000000,0.000000,0.000000
50%,50000.500000,18.527062,73.842373,4.000000,3.000000,12.00000,0.000000,0.000000,27.000000,0.000000,...,6.700000,458.000000,44.500000,22.900000,1.880000,5.900000,85.00000,0.000000,0.000000,0.000000
75%,75000.250000,18.575303,73.874290,6.000000,5.000000,18.00000,1.000000,0.000000,30.700000,1.500000,...,10.800000,849.000000,78.600000,31.600000,3.100000,13.400000,111.00000,0.000000,0.000000,0.000000
max,100000.000000,18.641080,73.950503,6.000000,6.000000,23.00000,1.000000,1.000000,47.100000,90.200000,...,53.300000,4130.000000,100.000000,65.300000,11.290000,96.700000,333.00000,1.000000,1.000000,1.000000

## Unique Values

In [6]:
print("Unique values in each column:")
print(df.nunique())

Unique values in each column:
record_id                      100000
timestamp                       91101
location_name                      20
latitude                        67358
longitude                       67145
road_type                           3
lane_count                          4
day_of_week                         7
hour                               24
is_weekend                          2
is_holiday                          2
weather_condition                   6
temperature_C                     349
rainfall_mm                       663
visibility_km                     981
humidity_percent                  801
wind_speed_kmph                   431
vehicle_count                    3022
occupancy_percent                 916
avg_speed_kmph                    588
travel_time_index                 458
signal_status                       3
public_transport_delay_min        742
pollution_index_aqi               297
event_nearby                        2
construction_work                   2
accident_reported                   2
accident_severity                   3
prev_hour_congestion                4
congestion_level                    4
target_congestion_next_hour         4
dtype: int64

# Health Report

In [7]:
health_report = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.astype(str),
    "Missing Values": df.isnull().sum(),
    "Unique Values": df.nunique()
})

health_report

,Column,Data Type,Missing Values,Unique Values
record_id,record_id,int64,0,100000
timestamp,timestamp,str,0,91101
location_name,location_name,str,0,20
latitude,latitude,float64,0,67358
longitude,longitude,float64,0,67145
road_type,road_type,str,0,3
lane_count,lane_count,int64,0,4
day_of_week,day_of_week,int64,0,7
hour,hour,int64,0,24
is_weekend,is_weekend,int64,0,2
is_holiday,is_holiday,int64,0,2
weather_condition,weather_condition,str,0,6
temperature_C,temperature_C,float64,0,349
rainfall_mm,rainfall_mm,float64,0,663
visibility_km,visibility_km,float64,0,981
humidity_percent,humidity_percent,float64,0,801
wind_speed_kmph,wind_speed_kmph,float64,0,431
vehicle_count,vehicle_count,int64,0,3022
occupancy_percent,occupancy_percent,float64,0,916
avg_speed_kmph,avg_speed_kmph,float64,0,588
travel_time_index,travel_time_index,float64,0,458
signal_status,signal_status,str,0,3
public_transport_delay_min,public_transport_delay_min,float64,0,742
pollution_index_aqi,pollution_index_aqi,int64,0,297
event_nearby,event_nearby,int64,0,2
construction_work,construction_work,int64,0,2
accident_reported,accident_reported,int64,0,2
accident_severity,accident_severity,str,97287,3
prev_hour_congestion,prev_hour_congestion,str,0,4
congestion_level,congestion_level,str,0,4
target_congestion_next_hour,target_congestion_next_hour,str,0,4

# MISSING DATA INVESTIGATION

## Find missing values

In [8]:
missing = df.isnull().sum()

print(missing[missing > 0])

accident_severity    97287
dtype: int64

## Calculate missing percentage

In [9]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

print(missing_percentage[missing_percentage > 0])

accident_severity    97.287
dtype: float64

In [10]:
pd.crosstab(
    df["accident_reported"],
    df["accident_severity"],
    dropna=False
)

accident_severity  Minor  Moderate  Severe    NaN
accident_reported
0                      0         0       0  97287
1                   1760       769     184      0

## Handle the missing values

In [13]:
df["accident_severity"] = df["accident_severity"].fillna("No Accident")
print(df["accident_severity"].value_counts())

accident_severity
No Accident    97287
Minor           1760
Moderate         769
Severe           184
Name: count, dtype: int64

## Verify missing values again

In [14]:
print(df.isnull().sum()[df.isnull().sum() > 0])

Series([], dtype: int64)

# DUPLICATE RECORDS INTEGRITY

## duplicate rows

In [15]:
duplicate_rows = df.duplicated().sum()

print("Duplicate Rows:", duplicate_rows)

Duplicate Rows: 0

## duplicate record IDs

In [17]:
duplicate_ids = df["record_id"].duplicated().sum()

print("Duplicate Record IDs:", duplicate_ids)

Duplicate Record IDs: 0

## whether every record ID is unique

In [18]:
print("Total Records:", len(df))
print("Unique Record IDs:", df["record_id"].nunique())

Total Records: 100000
Unique Record IDs: 100000

## Final integrity check

In [19]:
if df["record_id"].is_unique:
    print("Record ID Integrity: PASSED")
else:
    print("Record ID Integrity: FAILED")

Record ID Integrity: PASSED

## Remove duplicates if any exist

In [20]:
df = df.drop_duplicates()

print("Dataset Shape:", df.shape)

Dataset Shape: (100000, 31)

# TIME INTELLIGENCE

## Convert timestamp to datetime

In [22]:
df["timestamp"] = pd.to_datetime(df["timestamp"])
print(df["timestamp"].dtype)

datetime64[us]

## Extract date,year,month,day,hour

In [25]:
df["date"] = df["timestamp"].dt.date
df["year"] = df["timestamp"].dt.year
df["month"] = df["timestamp"].dt.month
df["day"] = df["timestamp"].dt.day
df["hour_from_timestamp"] = df["timestamp"].dt.hour
print(
    (df["hour"] == df["hour_from_timestamp"]).all()
)

True

## Extract day of week

In [29]:
df["day_name"] = df["timestamp"].dt.day_name()
df[["timestamp", "day_name"]].head()

            timestamp day_name
0 2024-01-01 00:04:00   Monday
1 2024-01-01 00:09:00   Monday
2 2024-01-01 00:11:00   Monday
3 2024-01-01 00:15:00   Monday
4 2024-01-01 00:16:00   Monday

In [30]:
df["day_name"].unique()

<ArrowStringArray>
['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
Length: 7, dtype: str

## Create time-period category

In [36]:
def classify_time(hour):
    if 5 <= hour < 12:
        return "Morning"
    elif 12 <= hour < 17:
        return "Afternoon"
    elif 17 <= hour < 21:
        return "Evening"
    else:
        return "Night"

df["time_period"] = df["hour"].apply(classify_time)

In [37]:
df["time_period"].value_counts()

time_period
Night        33357
Morning      29103
Afternoon    20611
Evening      16929
Name: count, dtype: int64

## traffic by time period

In [38]:
df.groupby("time_period")["vehicle_count"].mean()

time_period
Afternoon     451.239047
Evening      1176.228247
Morning       759.651857
Night         368.011482
Name: vehicle_count, dtype: float64

# KPI FOUNDATION

## Total number of records

In [39]:
total_records = len(df)

print("Total Records:", total_records)

Total Records: 100000

## Total vehicles

In [40]:
total_vehicles = df["vehicle_count"].sum()

print("Total Vehicles:", total_vehicles)

Total Vehicles: 63596763

## Average vehicle count

In [41]:
average_vehicles = df["vehicle_count"].mean()

print("Average Vehicle Count:", round(average_vehicles, 2))

Average Vehicle Count: 635.97

## Average speed

In [42]:
average_speed = df["avg_speed_kmph"].mean()

print("Average Speed:", round(average_speed, 2), "km/h")

Average Speed: 24.1 km/h

## Average road occupancy

In [43]:
average_occupancy = df["occupancy_percent"].mean()

print("Average Occupancy:", round(average_occupancy, 2), "%")

Average Occupancy: 53.55 %

## Average travel time index

In [44]:
average_tti = df["travel_time_index"].mean()

print("Average Travel Time Index:", round(average_tti, 2))

Average Travel Time Index: 2.49

## Total accidents

In [45]:
total_accidents = df["accident_reported"].sum()

print("Total Reported Accidents:", total_accidents)

Total Reported Accidents: 2713

## Average AQI

In [46]:
average_aqi = df["pollution_index_aqi"].mean()

print("Average AQI:", round(average_aqi, 2))

Average AQI: 92.5

## KPI table

In [47]:
kpi = {
    "Total Records": len(df),
    "Total Vehicles": df["vehicle_count"].sum(),
    "Average Vehicle Count": round(df["vehicle_count"].mean(), 2),
    "Average Speed (km/h)": round(df["avg_speed_kmph"].mean(), 2),
    "Average Occupancy (%)": round(df["occupancy_percent"].mean(), 2),
    "Average Travel Time Index": round(df["travel_time_index"].mean(), 2),
    "Average AQI": round(df["pollution_index_aqi"].mean(), 2),
    "Total Accidents": df["accident_reported"].sum()
}

kpi_table = pd.DataFrame(
    kpi.items(),
    columns=["KPI", "Value"]
)

kpi_table

                         KPI        Value
0              Total Records    100000.00
1             Total Vehicles  63596763.00
2      Average Vehicle Count       635.97
3       Average Speed (km/h)        24.10
4      Average Occupancy (%)        53.55
5  Average Travel Time Index         2.49
6                Average AQI        92.50
7            Total Accidents      2713.00

## Save the cleaned dataset

After completing the checks and cleaning steps above, save the processed dataframe for the environmental analysis notebook.

In [ ]:
df.to_csv("../data/traffic_intelligence_cleaned.csv", index=False)
print("Cleaned dataset saved to data/traffic_intelligence_cleaned.csv")